from pathlib import Path

from mass_town.disciplines.meshing import MeshingBackend, MeshingRequest, MeshingResult
from mass_town.storage.filesystem import ensure_directory


class MockMeshingBackend(MeshingBackend):
    name = "mock"

    def is_available(self) -> bool:
        return True

    def availability_reason(self) -> str | None:
        return None

    def generate_mesh(self, request: MeshingRequest) -> MeshingResult:
        output_directory = ensure_directory(request.output_directory)
        geometry_stem = (
            request.geometry_input_path.stem
            if request.geometry_input_path is not None
            else "synthetic-geometry"
        )
        mesh_path = output_directory / f"{geometry_stem}.mock.msh"
        quality = min(1.0, request.target_quality + 0.15)
        element_count = int(1000 + quality * 4000)
        mesh_path.write_text(
            "\n".join(
                [
                    "# Mock mesh generated by MassTown",
                    f"run_id: {request.run_id}",
                    f"quality: {quality}",
                    f"elements: {element_count}",
                    "",
                ]
            )
        )
        return MeshingResult(
            backend_name=self.name,
            mesh_path=mesh_path,
            quality=quality,
            element_count=element_count,
            metadata={"generator": "mock", "geometry_stem": geometry_stem},
        )
