max_iterations: 8
allowable_stress: 180.0
meshing:
  tool: mock
  target_quality: 0.75
fea:
  tool: tacs
  model_input_path: analysis/model.bdf
  case_name: static
  write_solution: true
initial_tasks:
  - geometry
  - mesh
  - fea
  - optimizer
