max_iterations: 11
allowable_stress: 180.0
meshing:
  tool: gmsh
  geometry_input_path: inputs/geometry/crank.stp
  mesh_dimension: 2
  step_face_selector: largest_planar
  output_format: bdf
  target_quality: 0.75
fea:
  tool: tacs
  case_name: static
  write_solution: true
  shell_setup:
    node_sets:
      left_bore:
        selector: boundary_loop
        family: inner
        order_by: centroid_x
        index: 0
      right_bore:
        selector: boundary_loop
        family: inner
        order_by: centroid_x
        index: 1
    boundary_conditions:
      - node_set: left_bore
        dof: "123456"
    loads:
      - node_set: right_bore
        load_key: force
        direction: [0.0, -1.0, 0.0]
        distribution: equal
initial_tasks:
  - geometry
  - mesh
  - fea
  - optimizer
