max_iterations: 11
allowable_stress: 180.0
meshing:
  tool: gmsh
  geometry_input_path: crank.stp
  mesh_dimension: 2
  step_face_selector: largest_planar
  output_format: bdf
  target_quality: 0.75
fea:
  tool: tacs
  case_name: static
  write_solution: true
initial_tasks:
  - geometry
  - mesh
  - fea
  - optimizer
